<script lang="ts">
  import { onMount } from "svelte";
  import { api } from "$lib/api";
  import MetricCard from "$lib/components/MetricCard.svelte";
  let month = new Date().toISOString().slice(0, 7); let message = "";
  type Kpi = { totalTickets:number; openTickets:number; avgFirstResponseMinutes:number|null; avgResolutionMinutes:number|null; slaCompliancePercent:number|null; avgRating:number|null; byCategory:{name:string;count:number}[]; byStatus:{status:string;count:number}[]; perAgent:{agentId:string;name:string;tickets:number;resolved:number;avgResolutionMinutes:number|null}[] };
  let kpi: Kpi | null = null;
  const duration=(minutes:number|null)=>minutes===null?"—":minutes<60?`${Math.round(minutes)} mnt`:`${Math.floor(minutes/60)}j ${Math.round(minutes%60)}mnt`;
  async function load(){ const [year,number]=month.split("-").map(Number); const from=new Date(year,number-1,1).toISOString(); const to=new Date(year,number,0,23,59,59).toISOString(); kpi=await api<Kpi>(`/kpi/overview?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`); }
  function download(){ window.location.href=`/api/reports/monthly?month=${encodeURIComponent(month)}`; }
  onMount(()=>load().catch(cause=>message=cause instanceof Error?cause.message:"Gagal memuat analitik"));
  $: maxCategory=Math.max(1,...(kpi?.byCategory.map(item=>item.count) ?? [1]));
</script>
<svelte:head><title>Analytics & SLA — Ticket.Ops</title></svelte:head>
<section><header class="section-header"><div><p class="section-code">04 / Analytics & SLA</p><h1>Service performance.</h1><p>Gunakan laporan ini untuk melihat kualitas respons, kepatuhan SLA, dan beban penyelesaian tim.</p></div><div class="controls"><label>Bulan<input type="month" bind:value={month} on:change={() => load().catch(cause=>message=cause instanceof Error?cause.message:"Gagal memuat analitik")} /></label><button class="ghost" on:click={download}>Unduh CSV</button></div></header>{#if message}<p class="error">{message}</p>{/if}{#if !kpi}<p class="loading">Memuat analitik layanan…</p>{:else}<div class="metrics"><MetricCard label="Total tiket" value={kpi.totalTickets} detail="Pada periode dipilih"/><MetricCard label="Kepatuhan SLA" value={kpi.slaCompliancePercent === null?"—":`${kpi.slaCompliancePercent}%`} detail="Tiket selesai tepat waktu"/><MetricCard label="Respons pertama" value={duration(kpi.avgFirstResponseMinutes)} detail="Rata-rata waktu respons"/><MetricCard label="Resolusi" value={duration(kpi.avgResolutionMinutes)} detail="Rata-rata penyelesaian"/></div><div class="analytics"><article class="surface"><p class="section-code">Distribusi kategori</p><h2>Fokus kebutuhan layanan</h2>{#if kpi.byCategory.length === 0}<p class="empty">Belum ada data kategori.</p>{:else}<div class="bars">{#each kpi.byCategory as item}<div><span>{item.name}</span><i><b style={`width:${item.count/maxCategory*100}%`}></b></i><strong>{item.count}</strong></div>{/each}</div>{/if}</article><article class="surface"><p class="section-code">Status tiket</p><h2>Posisi antrian</h2><div class="status-grid">{#each kpi.byStatus as item}<div><small>{item.status.replace("_"," ")}</small><strong>{item.count}</strong></div>{/each}</div><p class="note">Gunakan angka ini bersama dashboard untuk menentukan tiket yang perlu ditindaklanjuti terlebih dahulu.</p></article></div><article class="surface team"><p class="section-code">Performa agen</p><h2>Kapasitas dan penyelesaian</h2><div class="table-scroll"><table><thead><tr><th>Agen</th><th>Ditangani</th><th>Selesai</th><th>Rata-rata resolusi</th></tr></thead><tbody>{#each kpi.perAgent as agent}<tr><td><strong>{agent.name}</strong></td><td>{agent.tickets}</td><td>{agent.resolved}</td><td>{duration(agent.avgResolutionMinutes)}</td></tr>{/each}</tbody></table></div></article>{/if}</section>
<style>
  .section-header{display:flex;justify-content:space-between;align-items:flex-end;gap:1.5rem}.section-header h1{margin:.35rem 0 .55rem;font-size:clamp(1.8rem,4vw,2.7rem)}.section-header p:not(.section-code){max-width:610px;margin:0;color:var(--dim);font-size:.82rem;line-height:1.55}.controls{display:flex;align-items:flex-end;gap:.6rem}.controls label{display:grid;gap:.35rem;color:var(--dim);font-size:.68rem;font-weight:700}.controls input{padding:.62rem .7rem;font-size:.76rem}.controls button{padding:.68rem .8rem;font-size:.72rem}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem;margin-top:2rem}.analytics{display:grid;grid-template-columns:1.3fr 1fr;gap:1rem;margin-top:1rem}.surface{padding:1.2rem;border:1px solid var(--line);border-radius:14px;background:#fff;box-shadow:0 4px 18px rgb(16 42 82 / 4%)}.surface h2{margin:.35rem 0 0;font-size:1.05rem}.bars{display:grid;gap:.85rem;margin-top:1.4rem}.bars>div{display:grid;grid-template-columns:minmax(85px,1fr) 2fr 1.5rem;align-items:center;gap:.65rem;color:var(--dim);font-size:.74rem}.bars i{display:block;height:9px;overflow:hidden;border-radius:99px;background:#edf2f8}.bars b{display:block;height:100%;border-radius:99px;background:#1769e0}.bars strong{color:var(--bone);font-size:.75rem;text-align:right}.status-grid{display:grid;grid-template-columns:1fr 1fr;gap:.75rem;margin-top:1.4rem}.status-grid div{padding:.8rem;border-radius:10px;background:#f5f8fc}.status-grid small{display:block;color:var(--dim);font-size:.62rem;font-weight:700}.status-grid strong{display:block;margin-top:.3rem;font-size:1.35rem}.note,.empty{margin:1.2rem 0 0;color:var(--dim);font-size:.74rem;line-height:1.5}.team{margin-top:1rem}.table-scroll{overflow-x:auto;margin-top:1rem}table{width:100%;min-width:520px;border-collapse:collapse;font-size:.77rem}th{padding:.7rem 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line);color:var(--dim);font-size:.66rem;text-align:left}td{padding:.85rem 0;border-bottom:1px solid #eef2f7;color:var(--dim)}td strong{color:var(--bone)}.loading{color:var(--dim)}@media(max-width:760px){.section-header{align-items:flex-start;flex-direction:column}.controls{width:100%;align-items:stretch}.controls label{flex:1}.metrics,.analytics{grid-template-columns:1fr 1fr}}@media(max-width:470px){.metrics,.analytics{grid-template-columns:1fr}.controls{flex-direction:column}.controls button{width:100%}}
</style>
