<script lang="ts">
  import { onMount } from "svelte";
  import { api, ApiError, type User } from "$lib/api";

  let users: User[] = [];
  let createOpen = false;
  let copiedId: string | null = null;
  let name = "";
  let department = "";
  let errorMessage = "";
  let formError = "";

  async function load() { users = await api<User[]>("/users"); }
  onMount(() => { load().catch((cause) => { errorMessage = cause instanceof Error ? cause.message : "Gagal memuat user"; }); });
  async function copyCode(user: User) {
    if (!user.joinCode) return;
    try { await navigator.clipboard.writeText(user.joinCode); copiedId = user.id; window.setTimeout(() => { if (copiedId === user.id) copiedId = null; }, 1500); }
    catch { errorMessage = "Kode tidak dapat disalin"; }
  }
  async function create() {
    formError = "";
    try { await api<User>("/users", { method: "POST", body: JSON.stringify({ name, department: department || undefined }) }); name = ""; department = ""; createOpen = false; await load(); }
    catch (cause) { formError = cause instanceof ApiError ? cause.message : "Gagal membuat user"; }
  }
  async function regenerate(id: string) { try { await api(`/users/${id}/regenerate-code`, { method: "POST" }); await load(); } catch (cause) { errorMessage = cause instanceof Error ? cause.message : "Gagal regenerasi kode"; } }
  function formatDate(value: string) { return new Intl.DateTimeFormat("id-ID", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)); }
</script>
<svelte:head><title>Users &amp; Join Codes — Ticket.Ops</title></svelte:head>
<section><div class="section-header"><div><p class="section-code">05 / Admin & integration</p><h1>People, channels, control.</h1><p class="section-desc">Kelola requester dan join code sebagai pintu masuk aman ke layanan Telegram.</p></div><button class="primary" on:click={() => { formError = ""; createOpen = true; }}>+ Buat user</button></div>{#if errorMessage}<p class="error">{errorMessage}</p>{/if}<div class="integration reveal"><div><span class="ai-chip">Alur layanan</span><strong>Pengguna → Telegram → AI / rules → Ticket → Agen</strong><p>AI membantu membaca konteks, sedangkan pembuatan tiket dan keputusan layanan tetap mengikuti alur yang terkontrol.</p></div><a href="/tickets">Buka ticket queue →</a></div><div class="notice reveal" style="animation-delay:140ms">Berikan kode ini ke user untuk dimasukkan di bot Telegram <code>/start</code>.</div><div class="table-wrap reveal" style="animation-delay:180ms"><div class="table-scroll"><table><thead><tr><th>Nama</th><th>Departemen</th><th>Join Code</th><th>Telegram</th><th>Ticket</th><th>Dibuat</th><th>Aksi</th></tr></thead><tbody>{#each users as user}<tr><td class="name">{user.name}</td><td>{user.department ?? "—"}</td><td>{#if user.joinCode}<span class="code-wrap"><code>{user.joinCode}</code><button class="text-button" on:click={() => copyCode(user)}>{copiedId === user.id ? "Tersalin ✓" : "Salin"}</button></span>{:else}—{/if}</td><td><span class={user.telegramChatId ? "connected" : "pending"}>{user.telegramChatId ? "Terhubung" : "Belum terhubung"}</span></td><td>{user._count?.tickets ?? 0}</td><td>{formatDate(user.createdAt)}</td><td><button class="regenerate" on:click={() => regenerate(user.id)}>Regenerasi</button></td></tr>{:else}<tr><td colspan="7" class="empty">Belum ada user. Buat user pertama untuk memulai.</td></tr>{/each}</tbody></table></div></div></section>
{#if createOpen}<div class="modal-backdrop" role="presentation" on:click={(event) => { if (event.target === event.currentTarget) createOpen = false; }}><div class="modal" role="dialog" aria-modal="true" aria-labelledby="user-title" tabindex="-1"><div class="modal-head"><div><p class="section-code">DIRECTORY ENTRY</p><h2 id="user-title">Buat User</h2></div><button class="close" on:click={() => createOpen = false} aria-label="Tutup">×</button></div><form on:submit|preventDefault={create}><label>Nama<input bind:value={name} required placeholder="Nama lengkap" /></label><label>Departemen (opsional)<input bind:value={department} placeholder="cth. Keuangan" /></label>{#if formError}<p class="error">{formError}</p>{/if}<div class="modal-actions"><button class="ghost" type="button" on:click={() => createOpen = false}>Batal</button><button class="primary" type="submit">Simpan</button></div></form></div></div>{/if}
<style>
  .section-header{display:flex;justify-content:space-between;align-items:flex-end;gap:2rem}.section-header h1{margin:.35rem 0 .55rem;font-size:clamp(1.8rem,4vw,2.7rem)}.section-desc{max-width:620px;margin:0;color:var(--dim);font-size:.82rem;line-height:1.55}.primary,.ghost,.close{padding:.7rem 1rem;font-size:.72rem}.close{padding:.1rem .4rem;font-size:1.4rem}.integration{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin-top:1.5rem;padding:1rem 1.15rem;border:1px solid #b9e4ee;border-radius:14px;background:#fbfeff}.integration strong{display:block;margin-top:.45rem;color:#28536c;font-size:.85rem}.integration p{margin:.3rem 0 0;color:#668093;font-size:.73rem}.integration a{color:var(--cyan);font-size:.74rem;font-weight:700;text-decoration:none;white-space:nowrap}.notice{margin-top:1rem;padding:.8rem 1rem;border:1px solid #cfe2ff;border-radius:10px;background:#f8fbff;color:#2a5f9e;font-size:.74rem}.notice code{font-size:.76rem}.table-wrap{margin-top:1.25rem;overflow:hidden;border:1px solid var(--line);border-radius:14px;background:#fff;box-shadow:0 4px 18px rgb(16 42 82 / 4%)}.table-scroll{overflow-x:auto}table{width:100%;min-width:720px;border-collapse:collapse;font-size:.76rem}th{padding:.8rem 1rem;border-bottom:1px solid var(--line);color:var(--dim);font-size:.66rem;text-align:left}td{padding:.85rem 1rem;border-bottom:1px solid #eef2f7;color:var(--dim)}tr:last-child td{border:0}td.name{color:var(--bone);font-weight:700}.code-wrap{display:flex;align-items:center;gap:.5rem}.code-wrap code{padding:.25rem .45rem;border-radius:6px;background:#edf4ff;color:var(--acid);font-size:.68rem;font-weight:700}.text-button,.regenerate{padding:0;border:0;background:transparent!important;color:var(--acid)!important;font-size:.67rem;font-weight:700}.regenerate{color:var(--amber)!important}.connected,.pending{display:inline-block;padding:.26rem .48rem;border-radius:99px;font-size:.66rem;font-weight:700}.connected{background:#e8f7ef;color:var(--success)}.pending{background:#eef3fa;color:#62718a}.empty{padding:1.5rem;color:var(--dim);text-align:left}.modal-backdrop{position:fixed;inset:0;z-index:10;display:grid;place-items:center;padding:1rem;background:rgb(16 42 82 / 34%);backdrop-filter:blur(4px)}.modal{width:min(560px,100%);padding:1.5rem;border:1px solid var(--line);border-radius:16px;background:#fff;box-shadow:0 24px 80px rgb(16 42 82 / 20%)}.modal-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:1.5rem}.modal h2{margin:.35rem 0 0;font-size:1.5rem}.modal form{display:grid;gap:1rem}.modal label{display:grid;gap:.45rem;color:var(--dim);font-size:.7rem;font-weight:700}.modal input{padding:.75rem;font-size:.8rem}.modal-actions{display:flex;justify-content:flex-end;gap:.6rem;border-top:1px solid var(--line);padding-top:1rem}.error{font-size:.76rem}@media(max-width:760px){.section-header,.integration{align-items:flex-start;flex-direction:column}}
</style>
